### ISSUE TITLE
Segmentation fault (core dumped) on Pool->submit

### ISSUE THREAD

**Issue by tlsarles** [krakjoe/pthreads#693]
Environment
==========

PHP 7.1.3 (cli) (built: Apr 10 2017 15:32:18) ( ZTS )
Version => 3.1.7dev
CentOS6 / Kernel 2.6.32-642.el6.x86_64

'./configure' '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--target=x86_64-redhat-linux-gnu' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--with-libdir=lib64' '--with-config-file-path=/etc' '--with-config-file-scan-dir=/etc/php.d' '--with-mysql-sock=/var/lib/mysql/mysql.sock' '--with-mysqli=mysqlnd' '--with-pdo-mysql=mysqlnd' '--enable-pthreads=shared' '--enable-cli' '--enable-maintainer-zts' '--enable-sockets' '--enable-sysvsem' '--enable-sysvshm' '--enable-sysvmsg' '--with-apxs2=/usr/sbin/apxs' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'target_alias=x86_64-redhat-linux-gnu'

Summary
======

I am using Joe's example code from another thread : 
https://github.com/krakjoe/pthreads/issues/615

I've found that the line, which adds a Threaded to the Pool causes the fault. If I comment  it out, the script completes (Though it doesn't do anything interesting)

$pool->submit(new T($i+1));

It does however still output a Seg Fault when the script completes. (This is true with any script which uses pthreads.so) in this environment.

Reproducing Code
==============

```
class T extends Threaded {
  public function __construct($input) {
    $this->input = $input;
  }

  public function run() {
    $this->data = 2*3.141592*($this->input); //2*Pi*r
  }
}

class W extends Worker {
  public function run() {
  }
}

class P extends Pool {
  public $results = [];

  public function process() {

    while ($this->collect(function (Collectable $job) {
        $this->results
            [$job->input] = $job->data;
        return true;
      }));

    $this->shutdown();

    return $this->results;
  }
}

$i = 0;
$pool = new P(16, W::class);
do {
  $pool->submit(new T($i+1));
  $i++;
} while ($i < 16);


$data = $pool->process();
var_dump($data);
```

Expected Output
=============

[Expected Output] - a filled array

Actual Output
============

Segmentation fault (core dumped)

**Comment by tlsarles** [comment]
I added an --enable-debug, and now get the following:

/root/php-7.1.4/Zend/zend_hash.c(2001) : ht=0x7f81a803bdc8 is inconsistent
/root/php-7.1.4/Zend/zend_hash.c(62) : Bailed out without a bailout address!

**Comment by SirSnyder** [comment]
Line `$this->data = 23.141592($this->input); //2Pir` seems wrong. Please provide a runnable example.

**Comment by tlsarles** [comment]
Sorry, because I hadn't specified that that section was code, the Git Hub editor was parsing out the *s. I fixed it above

**Comment by SirSnyder** [comment]
I've fixed that issue with commit b52b0d8db2116b98597eafb3faf151ce8c755fa4. As long as krakjoe is busy, checkout my fork https://github.com/SirSnyder/pthreads/commits/php/71

**Comment by tpunt** [comment]
@tlsarles Can you please confirm whether this has been fixed in master yet? I cannot replicate your problem, and so I cannot see whether it has been fixed or not.

Failing that, @SirSnyder can you confirm that b52b0d8db2116b98597eafb3faf151ce8c755fa4 definitely does fix this issue? It's not immediately obvious to me how this problem relates to your fix.

**Comment by tlsarles** [comment]
No, I was unable to get past this. I tried to recompile with various commits. I can only presume that something is broken with my environment and am going to build a new box. I still have the existing VM though if you want it.

**Comment by krakjoe** [comment]
As far as I can tell, this was fixed ... if I'm wrong, please re-open ...
