### ISSUE TITLE
No subsequent thread is spawned after spawning the first thread

### ISSUE THREAD

**Issue by SaitamaSama** [krakjoe/pthreads#801]
Environment
==========

  * `PHP 7.3.0-dev (cli) (built: Dec  6 2017 01:36:21) ( ZTS DEBUG )`
  * pthreads:  ```3.1.7dev```
  * OS: Arch Linux

Summary
======

Thread spawns after the first spawn do not occur.
To reproduce run the html code in two tabs/browser processes, the first websocket connection gets accepted and is getting handled by a separate thread, whereas any furthermore websocket connections get accepted but no new thread is spawned.

Reproducing Code
==============

```
<?php declare(strict_types=1);
//var_dump((new ReflectionClass("Socket"))->getMethods(ReflectionMethod::IS_PUBLIC));
class WebSocketWorker extends \Thread {
    private $socket;

    public function __construct(?\Socket $socket) {
        $this->socket = $socket;
    }

    public function run() {
        $payload = $this->parse($this->socket->read(1024));

        if($payload['Upgrade'] === "websocket") {
            $webSocketKey = trim($payload['Sec-WebSocket-Key']);
            $toSendKey = base64_encode(sha1($webSocketKey . "258EAFA5-E914-47DA-95CA-C5AB0DC85B11", true));
            $payloadToSend = "HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: $toSendKey\r\n\r\n";

            $this->socket->write($payloadToSend, strlen($payloadToSend));
        } else {
            $this->socket->write("HTTP/1.0 200 OK\r\n\r\nOk.");
            $this->socket->close();
            return;
        }

        while (true) {
            $payload = $this->socket->read(2048);
            if(strlen($payload) !== 0) {
                var_dump($payload);
            }
        }
    }

    public function parse(string $payload) {
        // This parses the HTTP header, no problems here
        $e = explode("\r\n", $payload);
        $r = [];
        for($i = 0; $i < count($e); $i++) {
            if($e[$i] === '') {break;}
            if($i === 0) {
                $r['meta_data'] = $e[$i];
                continue;
            }
            $s = explode(': ', $e[$i]);
            $r[$s[0]] = $s[1];
        }
        return $r;
    }
}

$socket = new \Socket(AF_INET, SOCK_STREAM, SOL_TCP);

$rand = rand(1025, 9999);
$socket->bind("127.0.0.1", 9900);
$socket->listen(10);

while (1) {
    $client = $socket->accept();
    if ($client) {
        echo "New Connection" . PHP_EOL;
        $socketWorker = new WebSocketWorker($client);
        $socketWorker->start();
        echo "Got rid of an web socket cluster-fuck from main process!" . PHP_EOL;
    }
}
```

To create a simple websocket connection, run this html in a browser:

```
<html>
<script>
let ws = new WebSocket("ws://localhost:9900/ws");
ws.onerror = (e) => console.error(e);
ws.onopen = (e) => {console.log(e); ws.send("HAHAHA! I WIN!")};
</script>
</html>
```

Expected Output
=============

```
/usr/local/bin/php /home/saitama/PhpstormProjects/GG/server.php
New Connection
Got rid of an web socket cluster-fuck from main process!
string(28) "<binary_data>"
New Connection
Got rid of an web socket cluster-fuck from main process!
string(28) "<binary_data>"
```

Actual Output
============

```
/usr/local/bin/php /home/saitama/PhpstormProjects/GG/server.php
New Connection
Got rid of an web socket cluster-fuck from main process!
string(28) "<binary_data>"
New Connection
```

**Comment by SirSnyder** [comment]
Can you reproduce the issue with PHP 7.2.x ?

**Comment by SaitamaSama** [comment]
Okay, will try to reproduce and report back in ~an hour, currently trying to make php-7.2 executable load the pthreads module ;-)

**Comment by SirSnyder** [comment]
No hurry

**Comment by SaitamaSama** [comment]
Okay, so finally was able to set up php-7.2.1 and pthreads-3.1.7-dev; and yes the same spawn error is happening in here as well. 
![screenshot from 2018-01-18 20-38-08](https://user-images.githubusercontent.com/10518541/35104672-8a1e1f36-fc8f-11e7-8c72-ce8a4d3a7717.png)

**Comment by SirSnyder** [comment]
@SaitamaSama check out latest master, issue should be fixed

**Comment by SaitamaSama** [comment]
Hmm, quite odd, I pulled the latest master branch, and compiled and installed it. And the script still isn't able to spawn subsequent threads, after the first one. The execution is blocked after accepting the connection :confused:

**Comment by SaitamaSama** [comment]
Any update on this :) @SirSnyder?

**Comment by SirSnyder** [comment]
I've tested your script via telnet and it works for me. Did you turned on the error reporting?

**Comment by SaitamaSama** [comment]
I do have it on, and even sprinkled `error_reporting(E_ALL)` all over the code, still there neither any error nor a new thread is spawned.

**Comment by dktapps** [comment]
Make sure you set `display_startup_errors` to `1` in your INI directives. That often silently swallows errors (see #761 )

**Comment by SirSnyder** [comment]
Indeed, concurrent requests were not processed. You have to keep and collect the references of your WebSocketWorker threads. See my [gist](https://gist.github.com/SirSnyder/1ce7da9129ba18a6c094b93570c9cec3). Additionally the threads should carefully be joined if the websocket was processed and is finished, to prevent unexpected behavior.

**Comment by SaitamaSama** [comment]
Okay, mm, makes sense...
